### ISSUE TITLE
Create services page

### ISSUE THREAD

**Issue by dustingraves** [secseattle/secseattle.github.io#11]
Use `services-2.html` as a starter.

http://preview.webpixels.ro/boomerang-v2.0.2/services-2.html

**Comment by alyssa-white** [comment]
For the three different categories Aaron wants them to be labeled as:

Sterling Commercial
Sterling Residential 
Sterling Excavation

**Comment by alyssa-white** [comment]
![commercial-services](https://cloud.githubusercontent.com/assets/12280265/13653261/739c507c-e605-11e5-8ebe-ff95def04403.jpg)

![residential-services](https://cloud.githubusercontent.com/assets/12280265/13653260/70eab09e-e605-11e5-9f6e-b6137ae54f51.jpg)

![excavation-services](https://cloud.githubusercontent.com/assets/12280265/13653258/67112aee-e605-11e5-8d7c-f869b2953d0b.jpg)
