### ISSUE TITLE
Provide 1920x1080 images for home page

### ISSUE THREAD

**Issue by dustingraves** [secseattle/secseattle.github.io#15]
Please provide a couple images that are 1920x1080 in resolution for the home page.

**Comment by alyssa-white** [comment]
![seattle-widescreen-new-wallpapers-for-background-free-download](https://cloud.githubusercontent.com/assets/12280265/13654182/749339b8-e60b-11e5-93cb-9ce298e7502f.jpg)

![photo-1455761808036-f54c1109ecbf](https://cloud.githubusercontent.com/assets/12280265/13654541/db530ad2-e60d-11e5-9bcf-ad4391c5253f.jpg)

![photo-1448745799564-e2c1ed534c94](https://cloud.githubusercontent.com/assets/12280265/13654619/3b2cddde-e60e-11e5-88c2-805521c28f96.jpg)
