### ISSUE TITLE
Pick Home page components

### ISSUE THREAD

**Issue by dustingraves** [secseattle/secseattle.github.io#18]
From the 3 pages below please select what parts you would like on the index page for the new site.

http://preview.webpixels.ro/boomerang-v2.0.2/homepage-business-1.html
http://preview.webpixels.ro/boomerang-v2.0.2/homepage-cover.html
http://preview.webpixels.ro/boomerang-v2.0.2/homepage-business-2.html

**Comment by alyssa-white** [comment]
Dustin,

They all kind of look the same, can you tell me what it is I'm looking for?

Thanks,

**Comment by alyssa-white** [comment]
So I think I like the second link the best. I'll ask Aaron if he wants to do a quote or something with the background showing through. But for now let's go with the following for the home page:

Our Company
Our Services (can we find little icons for commercial, residential and excavation?)
Portfolio Slide

**Comment by dustingraves** [comment]
so for the icons, you can choose from https://fortawesome.github.io/Font-Awesome/icons/ 

Maybe:
commercial - http://fortawesome.github.io/Font-Awesome/icon/building/
residential - http://fortawesome.github.io/Font-Awesome/icon/home/
excavation - http://fortawesome.github.io/Font-Awesome/icon/truck/ OR http://fortawesome.github.io/Font-Awesome/icon/cogs/

**Comment by dustingraves** [comment]
For Our Company what do you want it to say?

For Portfolio, what pictures/clients do you want featured?

**Comment by alyssa-white** [comment]
Commercial: http://fortawesome.github.io/Font-Awesome/icon/building/

Residential: http://fortawesome.github.io/Font-Awesome/icon/home/

Excavation: http://fortawesome.github.io/Font-Awesome/icon/exclamation-triangle/

**Comment by dustingraves** [comment]
What do you want the text to say in each of those?

**Comment by alyssa-white** [comment]
I just copied what's on the current website. You said in the future I can go and edit the text myself, right? I may sit down with Chris and Aaron at some to see if they want to change the wording.

Our Company:

At Sterling Electrical Contractors we know you have many choices to serve your electrical needs. We separate ourselves from our competitors by placing our customers first - that’s why we have so many smiling customers and enthusiastic referrals.

Expect the best from our experienced team:

 • We won’t “put you on the back burner” or fail to show up.
 • We won't surprise you with costly change orders and other extras.
 • We are on time
 • We treat you, your home, office, or project respectfully
 • We will communicate any price changes, problems, options, etc
 • We will complete your project on time and on budget

**Comment by alyssa-white** [comment]
Commercial:
• Troubleshooting inoperable electrical devices or appliance
• Add a circuit
• Replace old outlets
• Add dimmers, light switches or occupancy sensors
• Add new appliance circuit
• Replace or add new light fixture(s)
• Install smoke detectors
• Install CO sensors
• Add electric heaters

Residential: 
• New Construction Wiring
• Zonal Electrical Heating (Wall Mount Type Heaters)
• Installation and Wiring of Generators
• Installation and Upgrading of Electrical Services
• Interior Lighting
• Low Voltage/Intelligent Lighting Systems
• Landscape Lighting
• Security Lighting
• Multimedia Cabling (Audio, Video, Data)
• Computer Cabling/Networking
• Fiber Optics
• Phone Systems
• Home Automation (Lutron, Vantage, Litetouch)
• Surge Suppression 
• Swimming Pool and Hot Tub Wiring
• Multi-room audio and video
• Custom high-definition home theaters
• Multi-media entertainment systems
• Lighting control systems
• Surveillance cameras and recorders
• Gate and access controls
• Service Calls
• Generator Installation and Hookup

Excavation:
• Landscape lighting and power
• Underground service installs
• Street crossings
• Joint utility trenching and installation
• Vault installations
• Street lights
• Pedestrian lights

**Comment by dustingraves** [comment]
Are these for the square boxes with the icons?

**Comment by alyssa-white** [comment]
Portfolio: 

I'm not sure if Aaron wants to have a description for each job, but for now can we just put a photo and job name?

Chick-Fil-A: Lynnwood, WA
![img_4334](https://cloud.githubusercontent.com/assets/12280265/13754989/5483fe2c-e9d6-11e5-83fb-8bf498bf0ee3.JPG)

Moctezumas: Tukwila, WA
![unnamed 1](https://cloud.githubusercontent.com/assets/12280265/13755012/6983f4ee-e9d6-11e5-8aae-b0a81c37aa24.jpg)

Panera Bread: Tulalip, WA
![image2](https://cloud.githubusercontent.com/assets/12280265/13755038/8d045918-e9d6-11e5-8814-26696eb9c163.JPG)

Lynnwood Crossroads: Lynnwood, WA
![image](https://cloud.githubusercontent.com/assets/12280265/13755106/d9bd373e-e9d6-11e5-8698-babcb9d606c5.png)

**Comment by alyssa-white** [comment]
Yes, icons are for the square boxes.

**Comment by dustingraves** [comment]
Yes you will be able to edit the text easily.

**Comment by dustingraves** [comment]
The residential text seems to big aesthetically. These are just blurbs to take you to the page with more content.

**Comment by alyssa-white** [comment]
Oh, sorry. I see what you were asking. Aaron is gone, let me see what he would like to say in the small square boxes on the home page for services.

Those bullet points should be for when they click on an individual box.

**Comment by dustingraves** [comment]
Ok sounds good.

**Comment by alyssa-white** [comment]
Dustin, 

We decided to leave out the little blurbs in the services boxes.
