### ISSUE TITLE
FAQ missing resources

### ISSUE THREAD

**Issue by dustingraves** [secseattle/secseattle.github.io#35]
GET http://secseattle.github.io/assets/images/prv/person-3-75x75.png 404 (Not Found)
GET http://secseattle.github.io/assets/images/prv/person-2-75x75.png 404 (Not Found)

**Comment by egervais7** [comment]
Those are being used somewhere? Weird...
I'll get them back in there

**Comment by dustingraves** [comment]
these were small images decorating the video box on the right. Also that element and the content should be modifiable by end user.
