### ISSUE TITLE
Background Images

### ISSUE THREAD

**Issue by alyssa-white** [secseattle/secseattle.github.io#44]
Could you tell me how I can change out the background images on the home page in the future?

**Comment by dustingraves** [comment]
I have a change in for this Edd just needs to approve my merge request, you can now edit them from the `index.md`

**Comment by dustingraves** [comment]
https://github.com/secseattle/secseattle.github.io/pull/46/files

**Comment by dustingraves** [comment]
This is fixed. You can specify the image in the index.md. You just need to put the image file in /assets/images/.

**Comment by dustingraves** [comment]
You need at least 2 images but you can put as many of them as you want

**Comment by alyssa-white** [comment]
Great! Thanks!

Alyssa White
Sterling Electrical Contractors
6125 200th St SW
Lynnwood, WA 98036

[p](425) 774-1903
[f](425) 673-0760
