### ISSUE TITLE
Complete Descriptions in services page

### ISSUE THREAD

**Issue by dustingraves** [secseattle/secseattle.github.io#47]
Edit descriptions in service.md: https://github.com/secseattle/secseattle.github.io/blob/master/services.md

This will give you the 4 offer blurbs seen here:

http://secseattle.github.io/services/

If you don't want them or want less like 2 just delete 2 of the descriptions.

**Comment by alyssa-white** [comment]
So we're deciding to not go with these "offer" blurbs. Instead can we add 3 more "folders" I'll look for more photos and add those soon, as well as get descriptions added from Aaron.

The additions will be:
- Sterling Residential Contractors
- Service / Maintenence 
- Design Build

**Comment by alyssa-white** [comment]
Sterling Residential Contractors:
![residential contractors](https://cloud.githubusercontent.com/assets/12280265/16470999/c4fef3c8-3e0e-11e6-9528-677694b66d01.jpg)

Service / Maintenance: (this photo may be too small?)
![service maintenance](https://cloud.githubusercontent.com/assets/12280265/16471700/4203ad2e-3e13-11e6-84e3-4f530c6f5ad5.png)

Design Build:
![design build](https://cloud.githubusercontent.com/assets/12280265/16471006/d36a01fa-3e0e-11e6-96a8-9c8116131d94.jpg)

**Comment by alyssa-white** [comment]
Dustin, where can I find those icons that we used for the services on the home page? I was going to find some for the 3 services that we're adding.

**Comment by alyssa-white** [comment]
Here are the descriptions we'll use for the 3 new additions.

Design: Sterling Electrical Contractors prides itself on design capabilites. Our estimators and project managers work closely with CAD engineers to provide detailed drawings to meet our customers needs.

Service/Maintenance: Sterling Electrical Contractors also provides the service of troubleshooting in an effort to help maintain a quality product. We perform service and maintenance for the following: service calls, service upgrades, preventitive maintenance, and repairs.

Residential Contractors: Sterling Electrical Contractors services include mixed use, single family housing developments and remodels.

**Comment by dustingraves** [comment]
http://fontawesome.io/icons/ http://fontawesome.io/icons/

**Comment by alyssa-white** [comment]
Let's go with these icons:
- Sterling Residential Contractors: http://fontawesome.io/icon/users/
- Service / Maintenence: http://fontawesome.io/icon/wrench/
- Design Build: http://fontawesome.io/icon/comments-o/

**Comment by dustingraves** [comment]
Instead of the previous change you specified for getting rid of them and adding 3 more images?

**Comment by dustingraves** [comment]
https://github.com/secseattle/secseattle.github.io/issues/47#issuecomment-229504691

**Comment by alyssa-white** [comment]
So yeah we don't want that offer blurb that we originally had. We just want to add the 3 services to the home page as well. I saw you already have them added to the services section, looks great! I'll try to find a new maintenance photo, that one is terrible.

**Comment by alyssa-white** [comment]
Can we use this photo instead for Repair / Maintenance?

![cable](https://cloud.githubusercontent.com/assets/12280265/20407665/30049606-acc7-11e6-82d0-82ca3e9cca82.jpg)

**Comment by dustingraves** [comment]
yeah
