### ISSUE TITLE
Complete options in index.md

### ISSUE THREAD

**Issue by dustingraves** [secseattle/secseattle.github.io#48]
All of these are found in: https://github.com/secseattle/secseattle.github.io/edit/master/index.md

Line 11: Complete the service info sentences.

Line 22: Put a quote or any other random text you want to show in the section with the see through background on the home page.

Line 28: Change the text that shows on the image slider.

This will show as seen on: http://secseattle.github.io/

**Comment by egervais7** [comment]
It looks like a quote is still needed for this page to be completed. Currently has "this is an inspirational quote" on line 22

**Comment by alyssa-white** [comment]
I've added the quote! Can we get it more centered in the box?

**Comment by dustingraves** [comment]
When you say more centered, what do you mean?

**Comment by alyssa-white** [comment]
The quote just looks more towards the top of the box than centered. Not a big deal if it can't be done. ;)

**Comment by dustingraves** [comment]
I adjusted the position
