### ISSUE TITLE
Project pages

### ISSUE THREAD

**Issue by dustingraves** [secseattle/secseattle.github.io#52]
If you do not want a project description on the project pages please let us know and we will remove the "Project Description" title text that appears for each page.

**Comment by alyssa-white** [comment]
I asked Aaron awhile back and he does want a description. I haven't found time to sit down with him and go over that just yet, but we will!

**Comment by alyssa-white** [comment]
I was going to add some basic descriptions for the projects, but having a difficult time finding where to edit that?

**Comment by dustingraves** [comment]
If you go into the _projects folder, click on a project and edit it,  add the text in the empty space below the `---`. I added some dummy text here: https://github.com/secseattle/secseattle.github.io/blob/master/_projects/a-smokey-point.md to give you an example.

**Comment by alyssa-white** [comment]
Great, thanks! I've added a few but still putting together descriptions for the rest.
